# Jonathan's Drums Training Routine
# Exercises are presented sequentially. The kid does ALL exercises in order.
# Each exercise references lessons from lessons.yaml by ID.
#
# Target duration: ~25 minutes total
#
# Fields:
#   id:          Unique identifier for this exercise
#   title:       Display title for the exercise
#   description: Optional instructions for the kid
#   lessons:     List of lesson IDs the kid can pick from (at least 1 required)

exercises:
  - id: warmup
    title: "Warm Up"
    description: "Start with rudiments to get your hands moving"
    lessons:
      - rudiments-paradiddles-flam-drag
      - stroke-rolls
      - sixteenth-note-rests
      - basic-rhythms-and-beats
      - groove-practice-1
      - groove-practice-2

  - id: technique
    title: "Technique Practice"
    description: "Work on a specific technique — pick one and focus"
    lessons:
      - bass-drum-patterns
      - off-beat-drum-variations
      - sixteenth-notes-snare-hihat
      - beginner-drum-fills
      - more-fills
      - notebook-beats-and-fills

  - id: song-practice
    title: "Song Practice"
    description: "Pick a song and practice it — use the drum sheet and groovescribe links to help"
    lessons:
      - have-you-ever-seen-the-rain
      - back-in-black
      - comfortably-numb
      - yellow
      - forget-you
      - boulevard-of-broken-dreams
      - because-we-can
      - highway-to-hell

  - id: beat-exploration
    title: "Beat Exploration"
    description: "Try a new beat style — something different from regular rock drumming"
    lessons:
      - bossa-nova
      - mozambique

  - id: cool-down
    title: "Cool Down"
    description: "End with something fun — play a song you already know well"
    lessons:
      - have-you-ever-seen-the-rain
      - back-in-black
      - yellow
      - highway-to-hell
      - boulevard-of-broken-dreams
